version: "3.2"

services:
  reverse_proxy:
    image: "dtr.dev.acme.dckr.org/atsea/reverse-proxy"
    ports:
      - "8000:80"
      - "8443:443"
    secrets:
      - source: revprox_cert
        target: revprox_cert
      - source: revprox_key
        target: revprox_key
    networks:
      - front-tier

  database:
    image: dtr.dev.acme.dckr.org/atsea/database
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: atsea
    networks:
      - back-tier
    secrets:
      - postgres_password
  #  deploy:
  #    placement:
  #      constraints:
  #        - 'node.role == worker'

  appserver:
    image: dtr.dev.acme.dckr.org/atsea/app
    networks:
      - front-tier
      - back-tier
      - payment
    deploy:
      replicas: 1 
#      update_config:
#        parallelism: 2
#        failure_action: rollback
#      placement:
#        constraints:
#          - 'node.role == worker'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    secrets:
      - postgres_password

  payment_gateway:
    image: dtr.dev.acme.dckr.org/atsea/payment-gateway
    secrets:
      - source: staging_token
        target: payment_token
    networks:
      - payment
    deploy:
      update_config:
        failure_action: rollback
      placement:
        constraints:
    #      - 'node.role == worker'
          - 'node.labels.pcidss == yes'

networks:
  front-tier:
  back-tier:
  payment:
    driver: overlay
    driver_opts:
      encrypted: 'yes'

secrets:
  postgres_password:
    external: true
  staging_token:
    external: true
  revprox_key:
    external: true
  revprox_cert:
    external: true
